name = "react-router-v7-cloudflare"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "books-db"
database_id = "3c7fc518-58b7-4bb0-9637-b07944aad511"
migrations_dir = "./migrations"